/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  RouterHistory,
} from '@stencil/router';


export namespace Components {
  interface SimonGame {}
  interface SimonMain {
    'history': RouterHistory;
    'loss': boolean;
  }
  interface SimonTiles {
    'animationPattern': number[];
  }
}

declare global {


  interface HTMLSimonGameElement extends Components.SimonGame, HTMLStencilElement {}
  var HTMLSimonGameElement: {
    prototype: HTMLSimonGameElement;
    new (): HTMLSimonGameElement;
  };

  interface HTMLSimonMainElement extends Components.SimonMain, HTMLStencilElement {}
  var HTMLSimonMainElement: {
    prototype: HTMLSimonMainElement;
    new (): HTMLSimonMainElement;
  };

  interface HTMLSimonTilesElement extends Components.SimonTiles, HTMLStencilElement {}
  var HTMLSimonTilesElement: {
    prototype: HTMLSimonTilesElement;
    new (): HTMLSimonTilesElement;
  };
  interface HTMLElementTagNameMap {
    'simon-game': HTMLSimonGameElement;
    'simon-main': HTMLSimonMainElement;
    'simon-tiles': HTMLSimonTilesElement;
  }
}

declare namespace LocalJSX {
  interface SimonGame extends JSXBase.HTMLAttributes<HTMLSimonGameElement> {}
  interface SimonMain extends JSXBase.HTMLAttributes<HTMLSimonMainElement> {
    'history'?: RouterHistory;
    'loss'?: boolean;
  }
  interface SimonTiles extends JSXBase.HTMLAttributes<HTMLSimonTilesElement> {
    'animationPattern'?: number[];
    'onTileClicked'?: (event: CustomEvent<any>) => void;
  }

  interface IntrinsicElements {
    'simon-game': SimonGame;
    'simon-main': SimonMain;
    'simon-tiles': SimonTiles;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


