/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';
import {
  RouterHistory,
} from '@stencil/router';


export namespace Components {
  interface SimonGame {}
  interface SimonTiles {
    'animationPattern': number[];
  }
  interface SnGame {
    'history': RouterHistory;
  }
}

declare global {


  interface HTMLSimonGameElement extends Components.SimonGame, HTMLStencilElement {}
  var HTMLSimonGameElement: {
    prototype: HTMLSimonGameElement;
    new (): HTMLSimonGameElement;
  };

  interface HTMLSimonTilesElement extends Components.SimonTiles, HTMLStencilElement {}
  var HTMLSimonTilesElement: {
    prototype: HTMLSimonTilesElement;
    new (): HTMLSimonTilesElement;
  };

  interface HTMLSnGameElement extends Components.SnGame, HTMLStencilElement {}
  var HTMLSnGameElement: {
    prototype: HTMLSnGameElement;
    new (): HTMLSnGameElement;
  };
  interface HTMLElementTagNameMap {
    'simon-game': HTMLSimonGameElement;
    'simon-tiles': HTMLSimonTilesElement;
    'sn-game': HTMLSnGameElement;
  }
}

declare namespace LocalJSX {
  interface SimonGame extends JSXBase.HTMLAttributes<HTMLSimonGameElement> {}
  interface SimonTiles extends JSXBase.HTMLAttributes<HTMLSimonTilesElement> {
    'animationPattern'?: number[];
    'onGamepadTouched'?: (event: CustomEvent<any>) => void;
  }
  interface SnGame extends JSXBase.HTMLAttributes<HTMLSnGameElement> {
    'history'?: RouterHistory;
  }

  interface IntrinsicElements {
    'simon-game': SimonGame;
    'simon-tiles': SimonTiles;
    'sn-game': SnGame;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


